services:
  postgres:
    build:
      context: ./repositories/database
      dockerfile: Dockerfile.dev
    volumes:
      - "./repositories/database/entrypoint-scripts:/docker-entrypoint-initdb.d"
      - "./repositories/database/app-db-data:/var/lib/postgresql/data/"
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_PORT: 5432
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_MULTIPLE_DATABASES: list_db